/* automatically generated by rust-bindgen 0.69.5 */


// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0


#![allow(unused_imports, non_camel_case_types)]

use crate::api::*;


extern "C" {
    #[doc = " Allows IP addresses in the Common Name (CN) field to be used for hostname validation.\n\n By default, s2n-tls rejects certificates that contain an IP address in the CN field when no\n Subject Alternative Name (SAN) extension is present. This is in accordance with RFC 6125\n section 6.4.4, which states that the CN fallback only applies to fully qualified DNS domain\n names, and section 6.2.1, which requires IP reference identities to match only iPAddress SAN\n entries.\n\n Some legacy PKIs issue certificates with IP addresses in the CN field and no iPAddress SAN\n entry. `s2n_config_allow_ip_in_cn()` may be called to temporarily allow these certificates\n to pass hostname validation while re-issuing certs with proper iPAddress SAN entries.\n\n @param config The associated connection config.\n @returns S2N_SUCCESS on success, S2N_FAILURE on failure."]
    pub fn s2n_config_allow_ip_in_cn(config: *mut s2n_config) -> ::libc::c_int;
}
