/* automatically generated by rust-bindgen 0.69.5 */


// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0


#![allow(unused_imports, non_camel_case_types)]

use crate::api::*;


extern "C" {
    #[doc = " @deprecated Thread-local random state has been removed. This function is a\n no-op kept for backwards compatibility.\n\n @returns S2N_SUCCESS on success. S2N_FAILURE on failure"]
    pub fn s2n_cleanup_thread() -> ::libc::c_int;
}
