/* automatically generated by rust-bindgen 0.69.5 */


// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0


#![allow(unused_imports, non_camel_case_types)]

use libc::{iovec, FILE, off_t};
// specify that aws-lc-rs is used, so that the rust compiler will link in the appropriate
// libcrypto artifact.
#[cfg(not(s2n_tls_external_build))]
extern crate aws_lc_rs as _;

use crate::api::*;


pub const S2N_DEBUG_LOGS: u32 = 1;
pub const PRINT_BUFFER_SIZE: u32 = 256;
#[doc = " Set the logging callback to be used globally across s2n-tls.\n\n We use a global logging function because it's significantly more ergonomic than\n having to thread a config/connection into every log statement"]
pub type s2n_log_fn = ::core::option::Option<
    unsafe extern "C" fn(
        message: *const u8,
        module: *const ::libc::c_char,
        line_number: ::libc::c_int,
        function: *const ::libc::c_char,
    ),
>;
extern "C" {
    pub static mut s2n_global_log: s2n_log_fn;
}
extern "C" {
    pub fn s2n_set_global_log(cb: s2n_log_fn);
}
