/* automatically generated by rust-bindgen 0.65.1 */


// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0


#![allow(unused_imports, non_camel_case_types)]

use libc::{iovec, FILE, off_t};
// specify that aws-lc-rs is used, so that the rust compiler will link in the appropriate
// libcrypto artifact.
#[cfg(not(s2n_tls_external_build))]
extern crate aws_lc_rs as _;

use crate::api::*;


extern "C" {
    #[doc = " Turns on support for the NPN extension.\n\n This will allow an s2n-tls client to send the NPN extension and an s2n-tls\n server to respond to receiving the NPN extension. However, if their peer\n also indicates support for the ALPN extension, s2n-tls will prefer that.\n\n Use s2n_config_append_protocol_preference() to set up a list of supported protocols.\n After the negotiation for the connection has completed, the agreed-upon protocol\n can be retrieved with s2n_get_application_protocol().\n\n @param config A pointer to the config object\n @param enable Set to true to enable. Set to false to disable.\n @returns S2N_SUCCESS on success, S2N_FAILURE on error."]
    pub fn s2n_config_set_npn(config: *mut s2n_config, enable: bool) -> ::libc::c_int;
}
